import type { Address, ReturnDraft } from './types'

export const emptyAddress = (): Address => ({
  street: '',
  suite: '',
  city: '',
  state: '',
  zip: '',
})

export const createDefaultDraft = (): ReturnDraft => ({
  version: 3,
  currentStep: 0,
  scope: {
    domesticLlc: true,
    calendarYear: true,
    taxedAsPartnership: true,
    atLeastTwoPartners: true,
  },
  business: {
    legalName: '',
    ein: '',
    startDate: '2025-01-01',
    initialReturn: true,
    principalActivity: 'Custom computer programming services',
    productOrService: 'Software development services',
    businessCode: '541511',
    accountingMethod: 'cash',
    customAccountingMethod: '',
    irsFilingCenter: 'E-file',
    address: emptyAddress(),
  },
  partners: [
    {
      id: 'managing-member',
      ownerKind: 'individual',
      firstName: '',
      lastName: '',
      displayName: '',
      entityType: 'Individual',
      taxId: '',
      country: 'United States',
      immigrationStatus: 'unknown',
      customImmigrationStatus: '',
      taxPersonStatus: 'unknown',
      ownershipPercent: 50,
      profitPercent: 50,
      lossPercent: 50,
      capitalPercent: 50,
      isManagingMember: true,
      useBusinessAddress: true,
      address: emptyAddress(),
      beginningCapital: 0,
      capitalContributed: 0,
      cashDistributions: 0,
    },
    {
      id: 'partner-2',
      ownerKind: 'individual',
      firstName: '',
      lastName: '',
      displayName: '',
      entityType: 'Individual',
      taxId: '',
      country: 'United States',
      immigrationStatus: 'unknown',
      customImmigrationStatus: '',
      taxPersonStatus: 'unknown',
      ownershipPercent: 50,
      profitPercent: 50,
      lossPercent: 50,
      capitalPercent: 50,
      isManagingMember: false,
      useBusinessAddress: true,
      address: emptyAddress(),
      beginningCapital: 0,
      capitalContributed: 0,
      cashDistributions: 0,
    },
  ],
  allocations: {
    mode: 'ownership',
  },
  filing: {
    plannedFileDate: '2026-07-13',
    extensionFiled: 'unknown',
    schedulesK1Timely: 'unknown',
    lateReasonTemplate: 'first-year',
    lateReasonNotes: '',
  },
  finances: {
    beginningCash: 0,
    beginningCapital: 0,
    grossReceipts: 0,
    returnsAndAllowances: 0,
    memberContributions: 0,
    cashDistributions: 0,
    repairs: 0,
    rent: 0,
    taxesAndLicenses: 0,
    interest: 0,
    otherExpenses: [
      { id: 'expense-1', description: 'Software and online services', amount: 0 },
      { id: 'expense-2', description: 'Bank and payment processing fees', amount: 0 },
      { id: 'expense-3', description: 'Professional fees', amount: 0 },
    ],
  },
  complexity: {
    foreignActivity: false,
    foreignPartner: false,
    rentalActivity: false,
    inventory: false,
    employeesOrPayroll: false,
    contractor1099s: false,
    digitalAssets: false,
    debtOrLoanChanges: false,
    propertyOrEquipment: false,
    ownershipChanges: false,
    guaranteedPayments: false,
    taxCreditsOrElections: false,
  },
  representative: {
    sameAsManagingMember: true,
    firstName: '',
    lastName: '',
    phone: '',
    useManagingMemberAddress: true,
    address: emptyAddress(),
  },
})
